// Generated by scripts/generate-bocas-icons.mjs. Edit the generator, then regenerate.
import { forwardRef } from 'react'
import type { SVGProps } from 'react'

export type BocasIconProps = Omit<SVGProps<SVGSVGElement>, 'ref'> & {
  size?: number | string
  variant?: 'compact' | 'regular'
  strokeWidth?: number | string
}

function createBocasIcon(name: string, base: string[], detail: string[]) {
  const Icon = forwardRef<SVGSVGElement, BocasIconProps>(function BocasIcon(
    { size = 16, variant = 'compact', strokeWidth = 2, className, ...props }, ref
  ) {
    const labelled = Boolean(props['aria-label'] || props['aria-labelledby'])
    return (
      <svg ref={ref} xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24"
        width={size} height={size} fill="none" stroke="currentColor"
        strokeWidth={strokeWidth} strokeLinecap="round" strokeLinejoin="round"
        focusable="false" aria-hidden={labelled ? undefined : true}
        role={labelled ? 'img' : undefined}
        className={['inline-block shrink-0 align-middle', className].filter(Boolean).join(' ')}
        {...props}>
        {base.map((d, i) => <path key={'b' + i} d={d} />)}
        {variant === 'regular' && detail.map((d, i) => <path key={'d' + i} d={d} />)}
      </svg>
    )
  })
  Icon.displayName = name
  return Icon
}

export const MurchosIcon = createBocasIcon('MurchosIcon', ["M21 12a9 9 0 1 1-18 0 9 9 0 0 1 18 0Z","M7 14q2-3 5-1 3-2 5 1"], ["M7.5 9h2M14.5 9h2"])
export const TrophyIcon = createBocasIcon('TrophyIcon', ["M7 4h10v6a5 5 0 0 1-10 0ZM7 6H3v3q0 4 4 4M17 6h4v3q0 4-4 4M12 15v5M8 21h8"], ["M10 9q2-2 4 0"])
export const GiftIcon = createBocasIcon('GiftIcon', ["M4 10h16v10H4ZM3 6h18v4H3ZM12 6v14M12 6C3 6 6 0 12 6 18 0 21 6 12 6"], ["M6 15q2-2 4 0M14 15q2-2 4 0"])
export const XpIcon = createBocasIcon('XpIcon', ["M13 3 4 13h7l-1 8 10-11h-7Z"], [])
export const StreakIcon = createBocasIcon('StreakIcon', ["M12 3c1 5 6 6 6 11a6 6 0 0 1-12 0c0-3 2-5 4-7v5c2-2 2-5 2-9Z"], ["M9 16q3-3 6 0"])
export const ShopIcon = createBocasIcon('ShopIcon', ["M5 8h14l2 13H3ZM8 8V6a4 3 0 0 1 8 0v2","M8 15q2-2 4-1 2-1 4 1"], [])
export const MissionIcon = createBocasIcon('MissionIcon', ["M9 5H5v16h14V5h-4M9 3h6v4H9Z","M8 14l3 3 5-6"], [])
export const MedalIcon = createBocasIcon('MedalIcon', ["M8 12 4 3h6l2 5 2-5h6l-4 9M18 15a6 6 0 1 1-12 0 6 6 0 0 1 12 0Z"], ["M9 16q3-3 6 0"])
export const CrownIcon = createBocasIcon('CrownIcon', ["M4 18 3 6l5 4 4-7 4 7 5-4-1 12ZM7 21h10"], ["M8 15q2-2 4-1 2-1 4 1"])
export const BetIcon = createBocasIcon('BetIcon', ["M12 3 21 12 12 21 3 12Z","M9 12h.01M15 12h.01"], [])
export const AuctionIcon = createBocasIcon('AuctionIcon', ["M10 3 6 7l7 7 4-4ZM6 7 4 9M17 10l2-2M12 11l-8 8M13 21h8"], [])
export const ChatIcon = createBocasIcon('ChatIcon', ["M4 4h16v13H9l-5 4Z","M8 12q2-3 4-1 2-2 4 1"], ["M8 8h2M14 8h2"])
export const GameIcon = createBocasIcon('GameIcon', ["M7 6h10q3 0 4 11 0 4-5-1H8q-5 5-5 1Q4 6 7 6Z","M6 11h4M8 9v4M16 10h.01M18 13h.01"], [])
export const VoiceIcon = createBocasIcon('VoiceIcon', ["M4 14v-3a8 8 0 0 1 16 0v3M4 12H3v7h4v-7ZM20 12h1v7h-4v-7Z","M9 19q3-3 6 0"], [])
export const MusicIcon = createBocasIcon('MusicIcon', ["M9 17V6l11-3v11M9 10l11-3M9 17c0 4-6 5-6 2 0-2 3-3 6-2ZM20 14c0 4-6 5-6 2 0-2 3-3 6-2Z"], [])
export const SoundboardIcon = createBocasIcon('SoundboardIcon', ["M4 4h16v16H4ZM8 8h.01M16 8h.01M8 12h.01M16 12h.01","M8 17q2-2 4-1 2-1 4 1"], [])
export const PrinterIcon = createBocasIcon('PrinterIcon', ["M5 21V3h14v18M3 21h18M5 7h14M10 7v4l2 2 2-2V7M8 21v-5h8v5"], [])
export const ServerIcon = createBocasIcon('ServerIcon', ["M4 3h16v8H4ZM4 13h16v8H4ZM7 7h.01M7 17h.01","M12 7h5M12 18q2-3 5 0"], [])
export const BadgeIcon = createBocasIcon('BadgeIcon', ["M8 3h8l5 5v8l-5 5-4-3-4 3-5-5V8Z","M8 13q2-3 4-1 2-2 4 1"], ["M8 8h2M14 8h2"])
export const WalletIcon = createBocasIcon('WalletIcon', ["M4 8 17 3v5M4 8h16v13H4ZM20 12h-5v5h5"], ["M7 16q2-2 4 0"])
export const TipIcon = createBocasIcon('TipIcon', ["M11 3a5 5 0 1 1 0 10 5 5 0 0 1 0-10ZM3 16h5l3 3h5l4-4M3 21h13l5-5"], ["M9 9q2-2 4 0"])
export const QuizIcon = createBocasIcon('QuizIcon', ["M4 4h16v13h-7l-5 4v-4H4Z","M9 8c0-3 6-3 6 0 0 2-3 1-3 4M12 14h.01"], [])
export const ProfileIcon = createBocasIcon('ProfileIcon', ["M16 7a4 4 0 1 1-8 0 4 4 0 0 1 8 0ZM4 21v-2a8 5 0 0 1 16 0v2"], ["M8 19q2-2 4-1 2-1 4 1"])
export const TvIcon = createBocasIcon('TvIcon', ["M3 7h18v13H3ZM8 3l4 4 4-4","M8 15q2-3 4-1 2-2 4 1"], [])
